version: "3.8"

services:

  model-api:
    build: ./model
    ports:
      - "80:80"

  streamlit-app:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    environment:
      MODEL_API_URL: http://model-api:80/predict
    depends_on:
      - model-api
